### ISSUE TITLE
Feature Request: User-specific mount configuration

### ISSUE THREAD

**Issue by raamdev** [websharks/ubuntu-bootstrap#1]
It would be nice if I could have a `~/vagrant.mounts` file that the `/Vagrantfile` would read and load. That way I wouldn't have to change the mount locations in the `/Vagrantfile` every time I clone the repo to spin up a new VM.

**Comment by jaswrks** [comment]
Great idea. I made it possible to customize those using environment variables.
- See instructions [here](https://github.com/websharks/ubuntu-bootstrap#can-i-override-the-default-source-directories-for-wordpress). Those should make it easy to customize.

You could also take the `/Vagrantfile` in this repo and put that in `~/vagrant-mounts`. Then symlink the file into `ubuntu-bootstrap/Vagrantfile` after you clone the repo. The Vagrantfile is a ruby script, and that serves as the personal configuration file for most use cases; i.e., most flexible way to configure VMs.

Another way would be to fork this repo and customize just the Vagrantfile in your fork.

**Comment by jaswrks** [comment]
Note also that I was able to get read-only mounts to work again. So those mounts are now read-only again, which will prevent accidental deletion of a plugin repo while testing from the VM.

**Comment by jaswrks** [comment]
Another improvement (among many that I will document soon), is that Postfix is installed on the VM automatically now, which allows the VM to send email using PHP's `mail()` function w/o needing to configure something like WP Mail SMTP for quick tests.

---

I updated the README in this repo, so be sure to read back over it again. After you `vagrant up`, run:

```
$ vagrant ssh
$ sudo /bootstrap/installer
```

Or, to save time in a hurry...

```
$ vagrant ssh
$ sudo /bootstrap/installer --use-defaults
```

If you omit `--use-defaults`, you will be presented with an installation wizard and you can choose the software you want to test with; e.g., firewall on/off, MySQL, the PHP version, Apache or Nginx, etc.

**Comment by raamdev** [comment]
> which allows the VM to send email using PHP's mail() function w/o needing to configure something like WP Mail SMTP for quick tests.

For email-related testing, this is the coolest thing ever: http://mailcatcher.me/

[VVV](https://github.com/Varying-Vagrant-Vagrants/VVV) uses that and it's so incredibly helpful for testing--I used it a ton when I was testing Comment Mail.

**Comment by raamdev** [comment]
> I made it possible to customize those using environment variables.

Woohoo! Thank you. :-)
