### ISSUE TITLE
Feature Request: Installer config option to set up without SSL

### ISSUE THREAD

**Issue by raamdev** [websharks/ubuntu-bootstrap#11]
I prefer not to use SSL when testing locally and I found it challenging to disable SSL after setting up an instance of the Ubuntu Bootstrap (it required locating and modifying the VirtualHost entry in `/bootstrap/src/apache/.conf`). It would be nice if choosing not to use SSL were simply an option in the installer config wizard.

**Comment by jaswrks** [comment]
Hmm. It's seems easy enough, but I'm not sure I like this idea.

As we move toward HTTP/2 it's likely that the next big update to the Apache installer is going to be one that integrates the latest Apache advances toward HTTP/2 compatibility, which will absolutely require `https://`. I suppose at this time it would be a good opportunity to leave back compat. with the old Apache configuration though.

What is the reason why you prefer not to use `https://` locally? Just curious.

**Comment by raamdev** [comment]
> What is the reason why you prefer not to use https:// locally? Just curious.

Because for some reason installing the self-signed cert in my Keychain crashes my entire Mac (well, it freezes Keychain with an always-on-top window, which is impossible to kill, even with sudo and `kill`, and then all sorts of weird slowness starts to happen). And without installing the self-signed cert and selecting "Always Trust", I have to click through the annoying warning in my browser each time, which is a waste of time when I'm developing and testing locally. So, I turn off SSL on my local development sites.

**Comment by jaswrks** [comment]
Aha! So it's not just me. I experience the _exact_ same issue whenever I do that with any SSL certificate in the Keychain.app for some reason. However, if I power-down and then try it again it goes through OK and I have smooth sailing past that point.

Related issue here: https://discussions.apple.com/thread/6300609?tstart=0

**Comment by raamdev** [comment]
> However, if I power-down and then try it again it goes through OK and I have smooth sailing past that point.

I tried rebooting—at least a dozen times—to see if that would fix the issue, and I never did for me, so I eventually gave up.

**Comment by jaswrks** [comment]
Bummer. 😢

**Comment by Reedyseth** [comment]
I am also not able to setup the CA certificate to work with the green certificate( On Linux Debian environment), that is not a big issue but it would be cool also to work sometimes without the SSL certificate though.

> As we move toward HTTP/2 it's likely that the next big update to the Apache installer is going to be one that integrates the latest Apache advances toward HTTP/2 compatibility which will absolutely require https://

The migration process is going to be slow for many users, this is also another reason that I would to like use `http` as well, many users will be using the plugins in a not `https` sites.

This too as well:

@raamdev 

> I have to click through the annoying warning in my browser each time, which is a waste of time when I'm developing and testing locally. So, I turn off SSL on my local development sites.

**Comment by jaswrks** [comment]
I would suggest trying again to get the CA installed on your end. If you're on a Mac there are several [examples here](https://discussions.apple.com/thread/6300609?tstart=0) where people have had a similar problem but were able to work around the issue by restarting fresh and then setting it to 'Always Trust' a second time. Once installed, it's done and you don't need to do it again for any other VM that you create. So getting past this on a Mac is non-trivial, but worth the time.

@raamdev writes...

> choosing not to use SSL were simply an option in the installer config wizard.

Copy that. Yeah, I don't see any reason why that couldn't be a flag to the installer either.

---
- Referencing: https://github.com/websharks/ubuntu-bootstrap/blob/160501/src/apache/.conf#L234-L238
- Referencing: https://github.com/websharks/ubuntu-bootstrap/blob/160501/src/nginx/.conf#L200

**Comment by raamdev** [comment]
> So getting past this on a Mac is non-trivial, but worth the time.

I've spent, literally, about 4 or 5 full days worth of time (30+ hours) trying to get it to work. The only thing that's left for me to try is reinstalling my OS, so I'm not going to bother trying again until the time comes to replace my laptop. :-)

**Comment by jaswrks** [comment]
@Reedyseth writes...

> I am also not able to setup the CA certificate to work with the green certificate( On Linux Debian environment), that is not a big issue but it would be cool also to work sometimes without the SSL certificate though.

What browser are you using please?
See also: http://unix.stackexchange.com/a/90607

**Comment by jaswrks** [comment]
@raamdev: This works for me without issue...

``` bash
sudo security add-trusted-cert -k /Library/Keychains/System.keychain ~/projects/websharks/ubuntu-bootstrap/src/ssl/vm-ca-crt.pem
```

See also: https://derflounder.wordpress.com/2011/03/13/adding-new-trusted-root-certificates-to-system-keychain/

**Comment by raamdev** [comment]
This command worked for me:

```
sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain ~/projects/ubuntu-bootstrap/src/ssl/vm-ca-crt.pem
```

I needed the `-d` flag to add this certificate to admin certificate store; the default to store it in the user’s keychain caused the certificate to not be "always trusted". 

Magically, it now works fine for me! Woohoo!

---

**UPDATE by @jaswsinc:** In the command above that Raam used, don't forget to change `~/projects/ubuntu-bootstrap/src/ssl/vm-ca-crt.pem` so it points to your copy of the Ubuntu Bootstrap.

**Comment by Reedyseth** [comment]
> What browser are you using please?

I am using Chrome Version 51.0.2704.79 (64-bit). I don't think is the browser though, I will look around to see if I can make it work on Linux.

By the way, you have done an outstanding job on this Apache conf:
https://github.com/websharks/ubuntu-bootstrap/blob/160501/src/apache/.conf

**Comment by jaswrks** [comment]
@Reedyseth Thank you very much for the compliment :-)

---

Regarding Chrome on Linux. I can confirm this works on Ubuntu w/ Chrome and it looks like others have had success with this on other Linux variants as well. See: http://blog.avirtualhome.com/adding-ssl-certificates-to-google-chrome-linux-ubuntu/

**Comment by jaswrks** [comment]
@raamdev writes ...

Another reason for `http://` to be a possible configuration option in the WUB:

![2016-06-22_20-09-31](https://cloud.githubusercontent.com/assets/1563559/16288066/a13556aa-3894-11e6-8d73-6bd23f62da8d.png)

**Comment by raamdev** [comment]
Noting that adding the following to an MU plugin in `/app/src/wp-content/mu-plugins/` solves the above issue related to self-signed certificates:

``` php
add_filter('https_local_ssl_verify', '__return_false');
```

**Comment by jaswrks** [comment]
Next Release Changelog:
- New configuration option: `CFG_WEB_SERVER_SSL_ONLY` defaults to being off when the WUB is used together with Vagrant. When this is off it allows for a VM to be accessed over `http://` or `https://` and HSTS is completely disabled also. Props at @raamdev ~ See: https://github.com/websharks/ubuntu-bootstrap/issues/11
