### ISSUE TITLE
Local Bootstrap

### ISSUE THREAD

**Issue by jaswrks** [websharks/ubuntu-bootstrap#14]
Reported by @kristineds... The `bootstrap-me-flush-dns` file pulls in Bash includes for the WUB that normally expect Bash 4.0+ from the server (i.e., the VM), but when run locally against the default Mac `/bin/bash` (which is 3.x), it triggers the error:

``` bash
./src/bash/strict-mode: line 14: shopt: globstar: invalid shell option name
```
### Workaround for now ...

``` bash
$ brew install bash;
# Then restart your terminal window.
```

i.e., upgrade to Bash 4.0 on your Mac.

**Comment by kristineds** [comment]
@jaswsinc Upgraded my installation of Bash to 4.0, it works now! :)

**Comment by jaswrks** [comment]
Next Release Changelog:
- Drop dependencies from local bootstrap. See: #14
