### ISSUE TITLE
Warning: Failed opening '[...]/advanced-cache.php' for inclusion

### ISSUE THREAD

**Issue by raamdev** [websharks/ubuntu-bootstrap#16]
## EXPLANATION OF THE ISSUE

When installing and then deactivating Comet Cache, I get the following warning:

> Warning: include(/vagrant/src/app/src/wp-content/advanced-cache.php): failed to open stream: No such file or directory in /vagrant/src/app/src/wp-settings.php on line 74 Warning: include(): Failed opening '/vagrant/src/app/src/wp-content/advanced-cache.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /vagrant/src/app/src/wp-settings.php on line 74

This is running v160126 of WUBS with Apache installed instead of NGINX.
## STEPS TO REPRODUCE THE ISSUE

Install WUBS v160126, choose Apache in the installer. Install Comet Cache (latest version), activate, enable, then disable the plugin.
## BEHAVIOR THAT I EXPECTED

No warnings.
## BEHAVIOR THAT I OBSERVED

> Warning: include(/vagrant/src/app/src/wp-content/advanced-cache.php): failed to open stream: No such file or directory in /vagrant/src/app/src/wp-settings.php on line 74 Warning: include(): Failed opening '/vagrant/src/app/src/wp-content/advanced-cache.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /vagrant/src/app/src/wp-settings.php on line 74

**Comment by jaswrks** [comment]
@raamdev Thanks for reporting!

This may be caused by the abnormal `wp-config.php` file in the WUB. I'm going to remove this line when I work on #15 now that you've brought this to my attention. 

Referencing: https://github.com/websharks/ubuntu-bootstrap/blob/160622/src/wordpress/.wp-config.php#L3

**Comment by jaswrks** [comment]
Next Release Changelog:
- Remove `WP_CACHE` from default `wp-config.php` template file. See: #16
