### ISSUE TITLE
Feature Request: Mosh

### ISSUE THREAD

**Issue by raamdev** [websharks/ubuntu-bootstrap#20]
It would be great to have Mosh installed by default: https://mosh.org/ (Note that this requires a UDP port to be open; by default, mosh uses a UDP port between 60000 and 61000.)

Mosh is fantastic for maintaining SSH connections. You can get disconnected from your Internet connection, then reconnect and the SSH session will just resume.

**Comment by jaswrks** [comment]
Sounds awesome. I will try this out and then add it in.

**Comment by jaswrks** [comment]
Coming soon. Thanks for the tip!

**Comment by jaswrks** [comment]
Available starting with v170425.59362.
https://github.com/websharks/ubuntu-bootstrap/releases/tag/170425.59362
