### ISSUE TITLE
Feature Request: Mailcatcher

### ISSUE THREAD

**Issue by raamdev** [websharks/ubuntu-bootstrap#4]
It would be extremely useful to have [Mailcatcher](http://mailcatcher.me/) installed so that you can do testing that involves sending emails without actually needing to send email to a real email address.

[VVV](https://github.com/Varying-Vagrant-Vagrants/VVV) has this installed by default and it's probably the number one feature that I use when testing WordPress plugins that involve email routines (e.g., Comment Mail!).

**Comment by jaswrks** [comment]
Nice. I have seen that before but never used it. Looks helpful. I have no objection to adding it in. If you can install it on Ubuntu and paste in the commands (dependencies) that it has I can add a installation option for that to the bootstrap.

**Comment by raamdev** [comment]
Another +1 for this issue: It looks like right now this Vagrant box attempts to make connections to an external SMTP server. It would be nice to avoid outgoing SMTP connections altogether so that only Mailcatcher is used.

![2016-04-22_14-50-06](https://cloud.githubusercontent.com/assets/53005/14751768/98a1afb4-0899-11e6-829b-be253bb6a064.png)

**Comment by jaswrks** [comment]
Resolved by https://github.com/websharks/ubuntu-bootstrap/releases/tag/160501
