### ISSUE TITLE
Feature Request: Hostname-specific project directories in ~/.profile

### ISSUE THREAD

**Issue by raamdev** [websharks/ubuntu-bootstrap#5]
It's possible to [override the default source directories](https://github.com/websharks/ubuntu-bootstrap#can-i-override-the-default-source-directories-for-wordpress) like this in your `~/.profile`:

```
export WP_PROJECTS_DIR=~/my-projects/wordpress;
export WP_PERSONAL_PROJECTS_DIR=~/my-personal-projects/wordpress;
export WP_BUSINESS_PROJECTS_DIR=~/my-business-projects/wordpress;
```

However, what if you have 5 different VMs, each with a different hostname, and each with their own specific projects directory? 

It would be nice if it were also possible to define hostname-specific project directories in your `~/.profile`, e.g. `WS_VM_WP_PROJECTS_DIR` for the `ws.vm` hostname (dots converted to underscores).

**Comment by jaswrks** [comment]
Cool. That should be as simple as adding another `|| ENV[]` to lines like this.
https://github.com/websharks/ubuntu-bootstrap/blob/master/Vagrantfile#L14

However, my string manipulation skills in Ruby need some help before I can add that in; i.e., I need some help converting `ws.vm` into `WS_VM` in Ruby and then using that to build the `ENV[]` lookup there.

**Comment by jaswrks** [comment]
``` ruby
hostname_var = config.vm.hostname.upcase.tr('.-', '_');
print ENV["WP_#{hostname_var}_PROJECTS_DIR"]
```

**Comment by jaswrks** [comment]
Next Release Changelog:
- Hostname-specific environment variables for WordPress project paths. See: #5

**Comment by raamdev** [comment]
Sweet! Thank you. 😄
